### ISSUE TITLE
Repetitive time error

### ISSUE THREAD

**Issue by philchamp51** [SensorsIot/NTPtimeESP#16]
Hello. I have a problem.

The Lib works well for a few minutes and after it blocks at 07:28:16 - 7-2-2036 for about 3 minutes and so on, it works, it blocks, it works, it blocks and always with this same time and date 07:28:16 - 7-2-2036.

Do you have any idea about this problem?

**Comment by SensorsIot** [comment]
The lib checks if it got the time and if not, does not change anything. So it might be that your device does not get a valid time over a certain period.

**Comment by viniciusov** [comment]
@philchamp51 I'm experiencing this issue too, exactly as you described. 
Request#1 - Fail (Always the first one fails)
Request#2 - Success
Request#3 - Fail
Request#4 - Success... And so on....

Did you have success findind a workaround to this issue?
It's a shame because this lib is so simple to use!

**Comment by underwoodblog** [comment]
#21
