### ISSUE TITLE
#include error

### ISSUE THREAD

**Issue by PaulRB** [SensorsIot/NTPtimeESP#3]
Hi Andreas. Thanks for making this library. I found a small error that you will not have noticed.

In file NTPtimeESP.h, you put
`
# include <WiFiUDP.h>

`
This is OK for Widows, because file names are case-insentitive, but for Linux (and I think OSX) users, it gives a compile error. It should be:
`
# include <WiFiUdp.h>

`
I believe this change will be OK for Windows, Linux and OSX.

**Comment by lucaberta** [comment]
@PaulRB I discovered the very same issue you mention on my Linux machine, and you are right about the issue with the case.

I have also tested the issue on OS X El Capitan and, as I suspected, it did not surface since HFS+ partitions on Macs by default are not case-sensitive, although the filenames can show letters in different cases.

I will fork the library and perform the modification, let's see if @SensorsIot will merge it.

**Comment by SensorsIot** [comment]
Done
